package com.app.version_plugin


object Versions {

    const val junit = "4.13.2"
    const val androidx_test_ext_junit = "1.1.3"
    const val espresso_core = "3.4.0"
    const val core_ktx = "1.6.0"
    const val appcompat = "1.5.0"
    const val material = "1.6.1"
    const val activity_ktx = "1.2.3"
    const val fragment_ktx = "1.3.5"
    const val kotlinx_coroutines_core = "1.6.0"
    const val kotlinx_coroutines_android = "1.6.0"
    const val okhttp = "4.10.0"
    const val constraintlayout = "2.1.4"
    const val lifecycle_common_java8 = "2.3.1"
    const val lifecycle_extensions = "2.2.0"
    const val lifecycle_viewmodel_ktx = "2.5.0"
    const val lifecycle_livedata_ktx = "2.5.0"
    const val immersionbar = "3.2.2"
    const val immersionBarKtx = "3.2.2"
    const val XPopup = "2.8.15"
    const val mmkv = "1.0.22"
    const val retrofit = "2.9.0"
    const val converter_gson = "2.9.0"
    const val retrofit_url_manager = "1.4.0"
    const val PersistentCookieJar = "v1.0.1"

    const val glide = "4.12.0"
    const val coil = "2.2.2"
    const val lottie = "4.2.1"
    const val roundedimageview = "2.3.0"
    const val autosize = "1.2.1"
    const val agentweb_androidx = "4.1.4"
    const val BackgroundLibrary_libraryx = "1.7.5"
    const val bannerviewpager = "3.5.11"
    const val viewpagerindicator = "1.2.1"
    const val XXPermissions = "16.6"
    const val pictureselector = "v3.10.6"
    const val MagicIndicator = "1.7.0"
    const val BRV = "1.3.90"
    const val hms_scan = "1.3.2.300"
    const val leakcanary_android = "2.7"
    const val flex_box = "3.0.0"

    const val xPopupExt = "0.0.8"
    const val dkVideoPlayer = "3.3.5"
    const val baseRecyclerViewAdapterHelper = "4.0.0-beta04"
    const val pickerView = "4.1.9"
    const val shadowLayout = "3.3.2"
    const val room = "2.4.3"
    const val theRouter = "1.1.1"
    const val navigation = "2.5.3"
    const val header = "2.0.5"


}